### ISSUE TITLE
新手请教

### ISSUE THREAD

**Issue by qikong333** [snowlyg/iris-admin#30]
作者您好，我是刚学go不久，算接口仔的程度吧，然后这个东西拿上手不知道应该怎么使用好，文档很精简，但是我可能要写可看着操作的视频之类的东西，请问哪里可以找到啊

**Comment by snowlyg** [comment]
@qikong333 这个项目也是用来写接口的，没有视频类东西。
有几个参考实例项目，可以参考一下：

- [https://github.com/snowlyg/iris-admin-example](https://github.com/snowlyg/iris-admin-example)
- [https://github.com/snowlyg/iris-admin-job](https://github.com/snowlyg/iris-admin-job)

**Comment by qikong333** [comment]
好的，谢谢，就是把iris的功能集成了一下更方便使用的意思吗？因为我是个前端，对后端的架构理解不够深，当初自己去集成iris的时候确实觉得有点零散不知道怎么入手

**Comment by snowlyg** [comment]
@qikong333 嗯，差不多的意思。类似是一个后台管理接口开发的脚手架，兼容了 iris 和 gin 两个框架。

**Comment by qikong333** [comment]
好的，我试试先！努力学习中。。。
